### ISSUE TITLE
Hardware/Schaltplan

### ISSUE THREAD

**Issue by nighi** [steff393/hgdo#3]
Hallo,
super Projekt! Ich konnte bisher kaum Informationen zur Hardware finden. Hast du dir eine eigene Platine designed? Gibt es einen Schaltplan?

**Comment by steff393** [comment]
Hallo nighi,
ich hätte noch ein paar Platinen aus meiner Bestellung übrig, schick mir doch bitte eine Mail an wbec393@gmail.com

**Comment by malu254** [comment]
Hallo @steff393 , 
sorry das ich diesen Issue nochmals wiederverwende. Ich finde das Projekt super. Mir geht es allerdings wie @nighi ich kann keine Informationen zur Platine finden. Hast du mir zufällig die Gerber Files mit Bom und Pick and Place. Oder besteht die Möglichkeit, das ich dir noch 2 Platinen abkaufe?
