### ISSUE TITLE
RJ12 verbinden

### ISSUE THREAD

**Issue by tairogriz** [steff393/hgdo#6]
Hallo, 
wäre es denn möglich, bekannt zu geben, wie ich den ESP an die RJ12 Buchse löten muss? 
Also welche Pins an welche Ader? Und ob zB. noch ein RS485 Konverter dazwischen geschaltet werden muss?
Oder habe ich diese Informationen irgendwo übersehen?

**Comment by malu254** [comment]
Hallo zusammen, 
das würde mich auch sehr interessieren

**Comment by steff393** [comment]
s. https://github.com/steff393/hgdo/issues/3#issuecomment-1275082374
