### ISSUE TITLE
Gerber Files / BOM

### ISSUE THREAD

**Issue by ezcGman** [steff393/hgdo#7]
Hey Steff,

richtig geniales Projekt, well done! Viel Arbeit reingesteckt! Respekt!!

Ich würd mir wohl auch gern eine HGDO Platine zusammenbauen, aber ich finde nirgends die Gerber Files und BOM, um die Komponenten zu bestellen. Könntest du diese vielleicht noch zum Repo adden, sonst ist das ja irgendwie... witzlos, wenn es keiner nachbauen kann :D

Danke und LG,

Andy!

**Comment by steff393** [comment]
Hi, die Hardware-Daten sind nicht zur Veröffentlichung geplant.
