### ISSUE TITLE
Gerber Files / BOM

### ISSUE THREAD

**Issue by ezcGman** [steff393/hgdo#8]
Und nochmals, da mein altes Issue einfach **gelöscht** wurde. Was ist das bitte für eine Unart, ein Issue zu löschen, dass ganz nett und normal nach den Gerber Files fragt?

Wieso dokumentierst du dein Projekt so sehr und beschreibst, wie super es ist, wenn es niemand weder nachbauen noch käuflich erwerben kann? What's the point?

Wenn du Geld mit dem Projekt machen willst (was dein gutes Recht ist), dann veröffentliche das Projekt halt über z.B PCBWay Community und du kriegst nen Share für jede Bestellung, oder verkauf es direkt. Aber es gar nicht anzubieten und Nachfragen einfach zu löschen ist ein Unding, zumindest Letzteres.

Schreib halt wenigstens irgendwo in deine lange Dokumentation, warum man die Platine nicht erwerben kann.

Vielleicht liest das ja noch wer, bevor das hier auch gelöscht wird...

**Comment by steff393** [comment]
Das ist doch meine Sache, ob und wie ich meine privaten Projekte beschreibe. Ende der Diskussion, mir gefällt der Ton nicht.
